### ISSUE TITLE
1 раз прошел уровень на три звезды, 2 раз - на две, 3 раз - на одну. В меню остаются те же 3 звезды.

### ISSUE THREAD

**Issue by Jessica074** [Coykto/match3mages#51]

**Comment by Coykto** [comment]
Количество звёзд не должно уменьшаться. "Засчитывается" и запоминается только лучшая попытка. Так что если вы прошли уровень на 2 звезды, вы можете попытаться снова и улучшить результат, но если у вас не получится и вы закончите с 1 звездой, то ничего просто не произойдёт, однажды полученное достижение потерять уже нельзя.
