### ISSUE TITLE
Непредсказуемо срабатывают мечи и бомбы

### ISSUE THREAD

**Issue by Jessica074** [Coykto/match3mages#52]

**Comment by Coykto** [comment]
Меч имеет "направление" (из зеленого кружка исходят небольшие "стрелки") - оно обозначает будет ли убрана строка в которой находится меч или столбец. Бомба убирает все блоки на расстоянии 1 клетки от себя (включая себя). 

Если в "зоне поражения" меча или бомбы окажется ещё один меч или бомба, тогда для него дополнительно будут рассчитаны убираемые блоки, что можно описать как "цепная реакция".

Единственная проблема это отсутствие какой-либо задержки перед тем как эти "бонусы" сработают. Это может вызвать ощущение того что они не работают.  Это я исправлю.

**Comment by Coykto** [comment]
Отсутствие задержки = отсутствие визуального фидбека.

**Comment by Coykto** [comment]
Вроде как Done.
